const scheduleData = [
{
  subjectName: "Алгоритмизация и программировани",
  classType: "lecture",
  startTime: "08:30",
  endTime: "10:05",
  room: "304",
  building: "1",
  floor: "3",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "25.05.2026",
  weekday: "Пн"
},
{
  subjectName: "Алгоритмизация и программировани",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "304",
  building: "1",
  floor: "3",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-41",
  date: "25.05.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "422",
  building: "1",
  floor: "4",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "3",
  group: "ТВР-31",
  date: "25.05.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "14:15",
  endTime: "15:50",
  room: "404",
  building: "1",
  floor: "4",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "25.05.2026",
  weekday: "Пн"
},
{
subjectName: "Разработка мобильных приложений",
classType: "lecture",
startTime: "10:15",
endTime: "11:50",
room: "211",
building: "1",
floor: "2",
teacher: "Матс Николай Александрович",
classNumber: "2",
group: "ТВР-31",
date: "26.05.2026",
weekday: "Вт"
},
{
subjectName: "Разработка мобильных приложений",
classType: "practice",
startTime: "12:00",
endTime: "13:35",
room: "211",
building: "1",
floor: "2",
teacher: "Матс Николай Александрович",
classNumber: "3",
group: "ТВР-31",
date: "26.05.2026",
weekday: "Вт"
},
{
subjectName: "Управление инновационным проектом",
classType: "lecture",
startTime: "14:15",
endTime: "15:50",
room: "333",
building: "1",
floor: "3",
teacher: "Дьякова Оксана Валерьевна",
classNumber: "4",
group: "ТВР-31",
date: "26.05.2026",
weekday: "Вт"
},
{
subjectName: "Управление инновационным проектом",
classType: "practice",
startTime: "16:00",
endTime: "17:35",
room: "333",
building: "1",
floor: "3",
teacher: "Дьякова Оксана Валерьевна",
classNumber: "5",
group: "ТВР-31",
date: "26.05.2026",
weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программировани",
  classType: "lecture",
  startTime: "08:30",
  endTime: "10:05",
  room: "143",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "28.05.2026",
  weekday: "Чт"
},
{
  subjectName: "Алгоритмизация и программировани",
  classType: "laboratory",
  startTime: "10:15",
  endTime: "11:50",
  room: "143",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "28.05.2026",
  weekday: "Чт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "344",
  building: "1",
  floor: "3",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "3",
  group: "ТВР-31",
  date: "28.05.2026",
  weekday: "Чт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "laboratory",
  startTime: "14:15",
  endTime: "15:50",
  room: "344",
  building: "1",
  floor: "3",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "28.05.2026",
  weekday: "Чт"
},
{
subjectName: "Разработка мобильных приложений",
classType: "lecture",
startTime: "16:00",
endTime: "17:35",
room: "411",
building: "1",
floor: "4",
teacher: "Матс Николай Александрович",
classNumber: "5",
group: "ТВР-31",
date: "28.05.2026",
weekday: "Чт"
},
{
subjectName: "Разработка мобильных приложений",
classType: "laboratory",
startTime: "17:45",
endTime: "19:20",
room: "411",
building: "1",
floor: "4",
teacher: "Матс Николай Александрович",
classNumber: "6",
group: "ТВР-31",
date: "28.05.2026",
weekday: "Чт"
},
{
subjectName: "Управление инновационным проектом",
classType: "lecture",
startTime: "14:15",
endTime: "15:50",
room: "306",
building: "1",
floor: "3",
teacher: "Дьякова Оксана Валерьевна",
classNumber: "4",
group: "ТВР-31",
date: "29.05.2026",
weekday: "Пт"  
},
{
subjectName: "Управление инновационным проектом",
classType: "laboratory",
startTime: "16:00",
endTime: "17:35",
room: "306",
building: "1",
floor: "3",
teacher: "Дьякова Оксана Валерьевна",
classNumber: "5",
group: "ТВР-31",
date: "29.05.2026",
weekday: "Пт"  
},
{
  subjectName: "Алгоритмизация и программировани",
  classType: "lecture",
  startTime: "08:30",
  endTime: "10:05",
  room: "142",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "30.05.2026",
  weekday: "Сб"
},
{
  subjectName: "Алгоритмизация и программировани",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "142",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "30.05.2026",
  weekday: "Сб"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "223",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "30.05.2026",
  weekday: "Сб"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "223",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "5",
  group: "ТВР-31",
  date: "30.05.2026",
  weekday: "Сб"
},
{
subjectName: "Разработка мобильных приложений",
classType: "lecture",
startTime: "8:30",
endTime: "10:05",
room: "245",
building: "1",
floor: "2",
teacher: "Матс Николай Александрович",
classNumber: "1",
group: "ТВР-31",
date: "1.06.2026",
weekday: "Пн"
},
{
subjectName: "Разработка мобильных приложений",
classType: "laboratory",
startTime: "10:15",
endTime: "11:50",
room: "245",
building: "1",
floor: "2",
teacher: "Матс Николай Александрович",
classNumber: "2",
group: "ТВР-31",
date: "1.06.2026",
weekday: "Пн"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "08:30",
  endTime: "10:05",
  room: "144",
  building: "1",
  floor: "1",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "01.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "laboratory",
  startTime: "12:00",
  endTime: "13:35",
  room: "419",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "01.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "14:15",
  endTime: "15:50",
  room: "272",
  building: "1",
  floor: "2",
  teacher: "Матс Николай Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "01.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "8:30",
  endTime: "10:05",
  room: "101",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "02.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "101",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "02.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "202",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "3",
  group: "ТВР-31",
  date: "02.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "laboratory",
  startTime: "14:15",
  endTime: "15:50",
  room: "202",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "02.06.2026",
  weekday: "Вт"
},
 {
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "121",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "03.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "laboratory",
  startTime: "12:00",
  endTime: "13:35",
  room: "121",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "03.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "354",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "03.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "354",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "03.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "8:30",
  endTime: "10:05",
  room: "273",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "1",
  group: "ТВР-31",
  date: "05.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "273",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "2",
  group: "ТВР-31",
  date: "05.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "435",
  building: "1",
  floor: "4",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "05.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "14:15",
  endTime: "15:50",
  room: "435",
  building: "1",
  floor: "4",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "05.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "404",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "2",
  group: "ТВР-31",
  date: "06.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "laboratory",
  startTime: "12:00",
  endTime: "13:35",
  room: "404",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "06.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "303",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "06.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "303",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "06.06.2026",
  weekday: "Сб"
},
 {
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "167",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "08.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "laboratory",
  startTime: "12:00",
  endTime: "13:35",
  room: "167",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "08.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "222",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "08.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "laboratory",
  startTime: "16:00",
  endTime: "17:35",
  room: "222",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "5",
  group: "ТВР-31",
  date: "08.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "8:30",
  endTime: "10:05",
  room: "477",
  building: "1",
  floor: "4",
  teacher: "Матс Николай Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "09.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "477",
  building: "1",
  floor: "4",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "09.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "422",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "09.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "14:15",
  endTime: "15:50",
  room: "422",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "4",
  group: "ТВР-31",
  date: "09.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "367",
  building: "1",
  floor: "3",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "2",
  group: "ТВР-31",
  date: "10.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "laboratory",
  startTime: "12:00",
  endTime: "13:35",
  room: "367",
  building: "1",
  floor: "3",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "10.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "138",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "10.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "laboratory",
  startTime: "16:00",
  endTime: "17:35",
  room: "138",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "10.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "244",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "2",
  group: "ТВР-31",
  date: "12.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "244",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "3",
  group: "ТВР-31",
  date: "12.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "323",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "12.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "323",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "12.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "168",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "13.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "168",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "13.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "244",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "13.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "244",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "5",
  group: "ТВР-31",
  date: "13.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "125",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "15.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "125",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "15.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "234",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "15.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "234",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "5",
  group: "ТВР-31",
  date: "15.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "8:30",
  endTime: "10:05",
  room: "341",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "16.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "341",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "16.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "12:00",
  endTime: "13:35",
  room: "416",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "16.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "laboratory",
  startTime: "14:15",
  endTime: "15:50",
  room: "416",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "4",
  group: "ТВР-31",
  date: "16.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "134",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "17.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "laboratory",
  startTime: "16:00",
  endTime: "17:35",
  room: "134",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "17.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "17:45",
  endTime: "19:20",
  room: "308",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "6",
  group: "ТВР-31",
  date: "17.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "10:15",
  endTime: "11:50",
  room: "278",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "2",
  group: "ТВР-31",
  date: "19.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "478",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "19.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "laboratory",
  startTime: "10:15",
  endTime: "11:50",
  room: "367",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "20.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "445",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "20.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "148",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "22.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "148",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "22.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "287",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "22.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "287",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "5",
  group: "ТВР-31",
  date: "22.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "8:30",
  endTime: "10:05",
  room: "256",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "1",
  group: "ТВР-31",
  date: "23.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "laboratory",
  startTime: "10:15",
  endTime: "11:50",
  room: "256",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "2",
  group: "ТВР-31",
  date: "23.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "118",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "23.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "118",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "5",
  group: "ТВР-31",
  date: "23.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "laboratory",
  startTime: "8:30",
  endTime: "10:05",
  room: "107",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "24.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "laboratory",
  startTime: "10:15",
  endTime: "11:50",
  room: "214",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "2",
  group: "ТВР-31",
  date: "24.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Алгоритмизация и программирование",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "156",
  building: "1",
  floor: "1",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "24.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Основы создания искусственного интеллекта",
  classType: "practice",
  startTime: "14:15",
  endTime: "15:50",
  room: "203",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "24.06.2026",
  weekday: "Ср"
},
{
  subjectName: "Экзамен",
  classType: "exam",
  startTime: "10:15",
  endTime: "12:00",
  room: "215",
  building: "1",
  floor: "2",
  teacher: "Смирнов Владимир Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "26.06.2026",
  weekday: "Пт"
},
{
  subjectName: "Экзамен",
  classType: "exam",
  startTime: "14:15",
  endTime: "16:00",
  room: "216",
  building: "1",
  floor: "2",
  teacher: "Кадомцев Максим Игоревич",
  classNumber: "4",
  group: "ТВР-31",
  date: "27.06.2026",
  weekday: "Сб"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "341",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "29.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "341",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "29.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "416",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "4",
  group: "ТВР-31",
  date: "29.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "416",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "5",
  group: "ТВР-31",
  date: "29.06.2026",
  weekday: "Пн"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "8:30",
  endTime: "10:05",
  room: "367",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "1",
  group: "ТВР-31",
  date: "30.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "laboratory",
  startTime: "10:15",
  endTime: "11:50",
  room: "367",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "30.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "445",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "30.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "laboratory",
  startTime: "14:15",
  endTime: "15:50",
  room: "445",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "4",
  group: "ТВР-31",
  date: "30.06.2026",
  weekday: "Вт"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "lecture",
  startTime: "10:15",
  endTime: "11:50",
  room: "308",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "2",
  group: "ТВР-31",
  date: "01.07.2026",
  weekday: "Ср"
},
{
  subjectName: "Разработка мобильных приложений",
  classType: "practice",
  startTime: "12:00",
  endTime: "13:35",
  room: "308",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "3",
  group: "ТВР-31",
  date: "01.07.2026",
  weekday: "Ср"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "lecture",
  startTime: "14:15",
  endTime: "15:50",
  room: "451",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "4",
  group: "ТВР-31",
  date: "01.07.2026",
  weekday: "Ср"
},
{
  subjectName: "Управление инновационным проектом",
  classType: "practice",
  startTime: "16:00",
  endTime: "17:35",
  room: "451",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "5",
  group: "ТВР-31",
  date: "01.07.2026",
  weekday: "Ср"
},
{
  subjectName: "Экзамен",
  classType: "exam",
  startTime: "14:15",
  endTime: "16:00",
  room: "315",
  building: "1",
  floor: "3",
  teacher: "Матс Николай Александрович",
  classNumber: "4",
  group: "ТВР-31",
  date: "03.07.2026",
  weekday: "Пт"
},
{
  subjectName: "Экзамен",
  classType: "exam",
  startTime: "12:00",
  endTime: "13:45",
  room: "415",
  building: "1",
  floor: "4",
  teacher: "Дьякова Оксана Валерьевна",
  classNumber: "3",
  group: "ТВР-31",
  date: "04.07.2026",
  weekday: "Сб"
}
];

module.exports = scheduleData;